services:
  - type: web
    name: lab4-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - fromDatabase:
          name: lab4-db
          property: connectionString
          envVarName: DATABASE_URL

databases:
  - name: lab4-db
    databaseName: lab4
    user: lab4_user
